### ISSUE TITLE
Web domain and SSL Certificates

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/iNaturalist#3]
Create appropriate web domains and SSL certificates

**Comment by matthewandrews** [comment]
Let me know what domain/s you need...

**Comment by temi** [comment]
Domains are -
1. australia.inaturalist.org
2. inaturalist.ala.org.au

**Comment by matthewandrews** [comment]
No worries, I'll register those and sort out the HTTPS certificates.

**Comment by peggynewman** [comment]
@matthewandrews, can we also do inaturalist.org.au and redirect it to inaturalist.ala.org.au?
Does that make any sense to you? It makes sense to me to do that. We talked about it in a meeting but I believe we were referring to inaturalist.com.au, which doesn't make as much sense to me now.

**Comment by matthewandrews** [comment]
Sounds good...  I can kick that process off now if you're happy to go ahead.

**Comment by peggynewman** [comment]
Very happy.

**Comment by matthewandrews** [comment]
So... for HTTPS we are probably going to need to use one primary domain e.g. inaturalist.org.au (I can arrange an HTTPS cert for that, and we can ask iNat to install that for our instance).  Then we can have inaturalist.ala.org.au rewrite to that... whether we can get australia.inaturalist.org to rewrite to inaturalist.org.au depends on whether the iNat admins are prepared to do that.

**Comment by temi** [comment]
@matthewandrews Did you suggest this because it is the easiest way to get a cert without iNat guys getting involved?
I think we should propose this to iNat and see if they have other ideas.

**Comment by matthewandrews** [comment]
Well it would make obtaining the certificate a bit easier, but that's not such a big deal. The issue is that whichever way we do it, the https setup is going to need a primary certificate, so we need to decide what that will be.  I'm suggesting inaturalist.org.au because I suspect that's a shorter/simpler domain to use for marketing than the others... and I'd prefer not to hand over our wildcard ALA certificate.   It might be best if I talk to iNat admins directly to discuss the cert install process and redirection options...

**Comment by ansell** [comment]
TLS certificates were created and deployed for `inaturalist.ala.org.au`:

https://crt.sh/?q=inaturalist.ala.org.au

If iNaturalist created any TLS certificates on their side it would be one of those in this list:

https://crt.sh/?q=inaturalist.org

The StatusCake check for `https://inaturalist.ala.org.au/` is also checking TLS certificate validity.

**Comment by ansell** [comment]
http://australia.inaturalist.org/ resolves and redirects to https://inaturalist.ala.org.au/, but https://australia.inaturalist.org/ doesn't resolve.

If our documentation all points to https://inaturalist.ala.org.au/ is that okay?

**Comment by matthewandrews** [comment]
I think so. We have settled on https://inaturalist.ala.org.au/ as the publicised address.

**Comment by ansell** [comment]
@peggynewman If you can confirm that our support documentation is or will be pointing to `https://inaturalist.ala.org.au/` this issue can be closed.

**Comment by peggynewman** [comment]
Yep that's ok.
